// ==================== PRODUCT DATA ====================
import type { Product, Category } from '../types'

export const PRODUCTS: Product[] = [
  {id:1,name:"Wireless Bluetooth Headphones Pro",price:29.99,originalPrice:59.99,category:"Electronics",rating:4.5,sold:2847,brand:"SoundMax",seller:"AudioWorld Store",description:"Premium wireless headphones with active noise cancellation, 30-hour battery life, and crystal-clear sound quality.",specs:"Driver: 40mm | Battery: 30h | Weight: 250g | Bluetooth: 5.0",colors:["#000","#fff","#1a73e8"],stock:156},
  {id:2,name:"Smart Watch Ultra Fitness Tracker",price:49.99,originalPrice:89.99,category:"Electronics",rating:4.3,sold:5120,brand:"TechFit",seller:"GadgetHub",description:"Advanced fitness tracker with heart rate monitoring, GPS tracking, sleep analysis, and 100+ workout modes.",specs:"Display: 1.4\" AMOLED | Battery: 7 days | Waterproof: IP68",colors:["#000","#333","#e74c3c"],stock:230},
  {id:3,name:"USB-C Fast Charging Cable 3-Pack",price:12.99,originalPrice:24.99,category:"Electronics",rating:4.7,sold:12400,brand:"ChargePro",seller:"Tech Essentials",description:"Premium braided USB-C cables with 100W fast charging support. 3-pack includes 3ft, 6ft, and 10ft lengths.",specs:"Length: 3ft/6ft/10ft | Power: 100W | Data: USB 3.0",colors:["#000","#fff"],stock:500},
  {id:4,name:"Portable Bluetooth Speaker Waterproof",price:34.99,originalPrice:69.99,category:"Electronics",rating:4.4,sold:3800,brand:"BassBoom",seller:"AudioWorld Store",description:"Powerful portable speaker with 360° sound, IPX7 waterproof rating, and 24-hour playtime.",specs:"Power: 20W | Battery: 24h | Waterproof: IPX7",colors:["#000","#1a73e8","#e74c3c"],stock:189},
  {id:5,name:"Men's Casual Cotton T-Shirt",price:14.99,originalPrice:29.99,category:"Fashion",rating:4.2,sold:8900,brand:"UrbanStyle",seller:"Fashion Hub",description:"Comfortable 100% cotton t-shirt with modern fit. Available in multiple colors.",specs:"Material: 100% Cotton | Fit: Regular | Sizes: S-3XL",colors:["#000","#fff","#1a73e8","#27ae60","#e74c3c"],stock:350},
  {id:6,name:"Women's Running Shoes Lightweight",price:39.99,originalPrice:79.99,category:"Fashion",rating:4.6,sold:6200,brand:"SpeedRun",seller:"SportZone",description:"Ultra-lightweight running shoes with responsive cushioning and breathable mesh upper.",specs:"Weight: 220g | Cushion: EVA | Upper: Mesh",colors:["#000","#fff","#e74c3c","#1a73e8"],stock:200},
  {id:7,name:"Stainless Steel Water Bottle 750ml",price:16.99,originalPrice:29.99,category:"Home",rating:4.8,sold:15600,brand:"HydroLife",seller:"Home Essentials",description:"Double-wall vacuum insulated water bottle. Keeps drinks cold 24h or hot 12h.",specs:"Capacity: 750ml | Material: 304 Stainless Steel",colors:["#c0392b","#2c3e50","#27ae60","#f39c12"],stock:800},
  {id:8,name:"LED Desk Lamp Dimmable Touch Control",price:24.99,originalPrice:49.99,category:"Home",rating:4.5,sold:4300,brand:"BrightHome",seller:"Home Essentials",description:"Modern LED desk lamp with 5 color modes and 10 brightness levels. USB charging port.",specs:"Power: 10W | Modes: 5 Color | Brightness: 10 Levels",colors:["#000","#fff"],stock:320},
  {id:9,name:"Vitamin C Face Serum Brightening",price:18.99,originalPrice:35.99,category:"Beauty",rating:4.4,sold:7800,brand:"GlowSkin",seller:"Beauty Palace",description:"Potent Vitamin C serum with hyaluronic acid and vitamin E. Brightens skin, reduces dark spots.",specs:"Volume: 30ml | Key: Vitamin C, Hyaluronic Acid",colors:[],stock:450},
  {id:10,name:"Professional Makeup Brush Set 12pcs",price:22.99,originalPrice:44.99,category:"Beauty",rating:4.6,sold:9200,brand:"GlamPro",seller:"Beauty Palace",description:"Complete 12-piece makeup brush set with synthetic bristles.",specs:"Pieces: 12 | Bristle: Synthetic | Handle: Wood",colors:["#f5c6d0","#2c3e50"],stock:600},
  {id:11,name:"Yoga Mat Non-Slip 6mm Thick",price:19.99,originalPrice:39.99,category:"Sports",rating:4.7,sold:11000,brand:"FlexFit",seller:"SportZone",description:"Premium non-slip yoga mat with alignment lines. 6mm thick for joint protection.",specs:"Thickness: 6mm | Size: 183x61cm | Material: TPE",colors:["#9b59b6","#1a73e8","#27ae60","#e74c3c"],stock:700},
  {id:12,name:"Resistance Bands Set of 5",price:15.99,originalPrice:29.99,category:"Sports",rating:4.5,sold:8400,brand:"FlexFit",seller:"SportZone",description:"Set of 5 resistance bands with different resistance levels.",specs:"Levels: 5 (10-50 lbs) | Material: Natural Latex",colors:["#e74c3c","#f39c12","#27ae60","#1a73e8","#9b59b6"],stock:900},
  {id:13,name:"Building Blocks Creative Set 500pcs",price:27.99,originalPrice:49.99,category:"Toys",rating:4.8,sold:6500,brand:"BuildMaster",seller:"Toy Land",description:"500-piece creative building block set compatible with major brands.",specs:"Pieces: 500 | Age: 6+ | Material: ABS Plastic",colors:[],stock:250},
  {id:14,name:"Remote Control Racing Car",price:32.99,originalPrice:59.99,category:"Toys",rating:4.3,sold:3200,brand:"SpeedRacer",seller:"Toy Land",description:"High-speed RC car with 2.4GHz remote control. Reaches speeds up to 30km/h.",specs:"Speed: 30km/h | Range: 50m | Battery: 1200mAh",colors:["#e74c3c","#1a73e8","#f39c12"],stock:180},
  {id:15,name:"Bestselling Novel Collection Box Set",price:45.99,originalPrice:89.99,category:"Books",rating:4.9,sold:2100,brand:"BookWorld",seller:"Book Haven",description:"Collection of 5 bestselling novels from award-winning authors.",specs:"Books: 5 | Format: Hardcover | Language: English",colors:[],stock:120},
  {id:16,name:"Programming Guide for Beginners",price:24.99,originalPrice:44.99,category:"Books",rating:4.6,sold:4800,brand:"CodePress",seller:"Book Haven",description:"Comprehensive guide to learning programming from scratch.",specs:"Pages: 450 | Format: Paperback | Language: English",colors:[],stock:300},
  {id:17,name:"Organic Green Tea Premium 100 Bags",price:11.99,originalPrice:22.99,category:"Food",rating:4.7,sold:9800,brand:"TeaNature",seller:"Organic Market",description:"Premium organic green tea sourced from high-altitude gardens.",specs:"Bags: 100 | Type: Organic Green Tea | Origin: Japan",colors:[],stock:1000},
  {id:18,name:"Protein Bar Variety Pack 24 Count",price:29.99,originalPrice:49.99,category:"Food",rating:4.4,sold:7200,brand:"FitFuel",seller:"Organic Market",description:"24-count variety pack of high-protein bars. 20g protein per bar.",specs:"Count: 24 | Protein: 20g/bar | Flavors: 6",colors:[],stock:400},
  {id:19,name:"Mechanical Gaming Keyboard RGB",price:44.99,originalPrice:79.99,category:"Electronics",rating:4.6,sold:5600,brand:"GamePro",seller:"GadgetHub",description:"Full-size mechanical keyboard with hot-swappable switches and RGB backlighting.",specs:"Switches: Mechanical | Backlight: RGB | Layout: Full",colors:["#000"],stock:280},
  {id:20,name:"Webcam HD 1080p with Microphone",price:29.99,originalPrice:54.99,category:"Electronics",rating:4.3,sold:4100,brand:"ClearView",seller:"GadgetHub",description:"Full HD 1080p webcam with built-in noise-cancelling microphone.",specs:"Resolution: 1080p | FPS: 30 | Mic: Built-in",colors:["#000"],stock:350},
  {id:21,name:"Women's Leather Crossbody Bag",price:35.99,originalPrice:64.99,category:"Fashion",rating:4.5,sold:3600,brand:"LuxeBag",seller:"Fashion Hub",description:"Elegant crossbody bag made from premium PU leather.",specs:"Material: PU Leather | Size: 25x18x8cm",colors:["#000","#8B4513","#c0392b","#f5c6d0"],stock:220},
  {id:22,name:"Scented Candle Set 6-Pack",price:19.99,originalPrice:34.99,category:"Home",rating:4.6,sold:5800,brand:"AromaHome",seller:"Home Essentials",description:"Set of 6 scented soy wax candles in premium glass jars.",specs:"Count: 6 | Material: Soy Wax | Burn: 30h each",colors:[],stock:500},
  {id:23,name:"Hair Dryer Professional 2000W",price:38.99,originalPrice:69.99,category:"Beauty",rating:4.4,sold:4500,brand:"StylePro",seller:"Beauty Palace",description:"Professional 2000W hair dryer with ionic technology.",specs:"Power: 2000W | Settings: 3 Heat, 2 Speed",colors:["#000","#f5c6d0"],stock:300},
  {id:24,name:"Camping Tent 2-Person Lightweight",price:55.99,originalPrice:99.99,category:"Sports",rating:4.5,sold:2800,brand:"OutdoorPro",seller:"SportZone",description:"Lightweight 2-person camping tent with rainfly. Easy setup in 5 minutes.",specs:"Capacity: 2P | Weight: 2.5kg | Waterproof: 3000mm",colors:["#27ae60","#f39c12"],stock:150},
  {id:25,name:"Puzzle 1000 Pieces Landscape",price:13.99,originalPrice:24.99,category:"Toys",rating:4.7,sold:3400,brand:"PuzzleWorld",seller:"Toy Land",description:"Beautiful 1000-piece jigsaw puzzle featuring stunning landscape photography.",specs:"Pieces: 1000 | Size: 70x50cm",colors:[],stock:400},
  {id:26,name:"Cookbook Healthy Recipes 200+",price:19.99,originalPrice:34.99,category:"Books",rating:4.5,sold:2600,brand:"ChefPress",seller:"Book Haven",description:"Over 200 healthy and delicious recipes with nutritional information.",specs:"Recipes: 200+ | Pages: 320 | Format: Hardcover",colors:[],stock:200},
  {id:27,name:"Mixed Nuts Premium Gift Box 1kg",price:34.99,originalPrice:59.99,category:"Food",rating:4.8,sold:4200,brand:"NutriNuts",seller:"Organic Market",description:"Premium mixed nuts gift box with almonds, cashews, pistachios, walnuts, and macadamia nuts.",specs:"Weight: 1kg | Contents: 5 types | Packaging: Gift Box",colors:[],stock:300},
  {id:28,name:"Wireless Mouse Ergonomic Silent",price:15.99,originalPrice:29.99,category:"Electronics",rating:4.4,sold:7600,brand:"ClickPro",seller:"Tech Essentials",description:"Ergonomic wireless mouse with silent clicks. Adjustable DPI up to 2400.",specs:"DPI: 800/1200/1600/2400 | Battery: 18 months",colors:["#000","#fff","#1a73e8"],stock:600},
  {id:29,name:"Denim Jacket Vintage Wash",price:42.99,originalPrice:79.99,category:"Fashion",rating:4.3,sold:2100,brand:"DenimCo",seller:"Fashion Hub",description:"Classic vintage wash denim jacket with comfortable fit.",specs:"Material: 100% Cotton Denim | Fit: Regular | Sizes: S-XXL",colors:["#4a6fa5","#2c3e50"],stock:180},
  {id:30,name:"Essential Oil Diffuser 500ml",price:26.99,originalPrice:49.99,category:"Home",rating:4.6,sold:6100,brand:"AromaHome",seller:"Home Essentials",description:"Ultrasonic essential oil diffuser with 500ml capacity. 7 color LED lights.",specs:"Capacity: 500ml | Runtime: 12h | Colors: 7 LED",colors:["#fff","#8B4513"],stock:350}
]

export const CATEGORIES: Category[] = [
  {name:"Electronics",icon:"📱",color:"#3498db"},
  {name:"Fashion",icon:"👗",color:"#e91e63"},
  {name:"Home",icon:"🏠",color:"#4caf50"},
  {name:"Beauty",icon:"💄",color:"#9c27b0"},
  {name:"Sports",icon:"⚽",color:"#ff9800"},
  {name:"Toys",icon:"🧸",color:"#f44336"},
  {name:"Books",icon:"📚",color:"#795548"},
  {name:"Food",icon:"🍕",color:"#ff5722"}
]
